version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "45:75:97:06:20:35:27:8e:a9:e0:bb:8a:21:7c:57:c1"
      - run: yarn install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build 
      - run:
          name: Disable Jekyll filename interpreter
          command: touch posts/.vuepress/dist/.nojekyll
      - run: 
          name: Install gh-pages
          command: npm install gh-pages
      - run:
          name: Configure git userdata
          command: git config user.email "ci-build@basement-code.pl" && git config user.name "ci-build"
      - run:
          name: Deploy to gh-pages
          command: chmod +x node_modules/gh-pages/bin/gh-pages.js && $_ --dotfiles --message "[skip ci] Updates" --dist posts/.vuepress/dist
